#!/usr/bin/env bash

# see https://midnight-commander.org/ticket/3165
#     for sane file sizes
#     Should compile from source or use du/ncdu?

set -eu
set -o pipefail

# sudo apt install mc xsel
sudo apt install mc wl-clipboard
mc
