#!/bin/bash

sudo add-apt-repository -y ppa:ubuntu-elisp
sudo apt-get update
sudo apt-get install emacs-snapshot

if [[ ! -d ~/.emacs.d ]]; then
  git clone https://github.com/ramblehead/.emacs.d.git ~/.emacs.d
fi
