#!/bin/bash

sudo add-apt-repository -s -y ppa:ubuntu-elisp
sudo apt-get update
sudo apt-get install emacs-snapshot emacs-snapshot-el

if [[ ! -d /usr/local/src/emacs ]]; then
  sudo mkdir -p /usr/local/src/emacs || exit $?
  sudo chown `id -u -n` /usr/local/src/emacs || exit $?
  sudo chmod g+ws /usr/local/src/emacs || exit $?
  FILEARC=`apt-cache showsrc emacs-snapshot | \
           grep -m 1 -o -e emacs-snapshot.*\.tar\.gz`
  tar -xzf $FILEARC -C /usr/local/src/emacs
  find /usr/local/src/emacs -print0 | xargs -0 chmod g+w
fi

# apt-get -d source emacs-snapshot
# apt-cache showsrc emacs-snapshot | grep -m 1 -o -e emacs-snapshot.*\.tar\.gz
# tar -xzf emacs-snapshot_94069-f6ef15c-emacs-25.1~ubuntu16.04.1.tar.gz -C ~/123
#
# 

if [[ ! -d /usr/local/share/emacs/site-lisp/site-start.d ]]; then
  mkdir -p /usr/local/share/emacs/site-lisp/site-start.d || exit $?
fi

if [[ ! -f /usr/local/share/emacs/site-lisp/subdirs.el ]]; then
  sudo cp ../root/usr/local/share/emacs/site-lisp/subdirs.el \
          /usr/local/share/emacs/site-lisp || exit $?
fi

if [[ ! -f /usr/local/share/emacs/site-lisp/site-start.el ]]; then
  sudo cp ../root/usr/local/share/emacs/site-lisp/site-start.el \
          /usr/local/share/emacs/site-lisp || exit $?
fi

if [[ -f ~/.profile ]]; then
  if ! grep -q -e EMACSLOADPATH ~/.profile; then
    if [[ -s ~/.profile ]]; then echo >> ~/.profile; fi
    echo "export EMACSLOADPATH=/usr/local/share/emacs/site-lisp:" \
    >> ~/.profile || exit $?
  fi
else
  echo "export EMACSLOADPATH=/usr/local/share/emacs/site-lisp:" \
  >> ~/.profile || exit $?
fi
