#!/bin/bash

sudo add-apt-repository -s -y ppa:ubuntu-elisp
sudo apt-get update
sudo apt-get install emacs-snapshot emacs-snapshot-el

# apt-get source emacs-snapshot

if [[ ! -d /usr/local/share/emacs/site-lisp/site-start.d ]]; then
  mkdir -p /usr/local/share/emacs/site-lisp/site-start.d || exit $?
fi

if [[ ! -f /usr/local/share/emacs/site-lisp/subdirs.el ]]; then
  sudo cp ../root/usr/local/share/emacs/site-lisp/subdirs.el \
          /usr/local/share/emacs/site-lisp || exit $?
fi

if [[ ! -f /usr/local/share/emacs/site-lisp/site-start.el ]]; then
  sudo cp ../root/usr/local/share/emacs/site-lisp/site-start.el \
          /usr/local/share/emacs/site-lisp || exit $?
fi

if [[ -f ~/.profile ]]; then
  if ! grep -q -e EMACSLOADPATH ~/.profile; then
    if [[ -s ~/.profile ]]; then echo >> ~/.profile; fi
    echo "export EMACSLOADPATH=/usr/local/share/emacs/site-lisp:" \
    >> ~/.profile || exit $?
  fi
else
  echo "export EMACSLOADPATH=/usr/local/share/emacs/site-lisp:" \
  >> ~/.profile || exit $?
fi
