#!/bin/bash

user_name="$1"
package_name="$user_name"
base_dir="/home/rhpm/packages"
home_dir="$base_dir/$package_name"

if [[ -z "${package_name// }" ]]; then
  echo "usage: $(basename "$0") package_name"
  exit 1
fi

sudo useradd --system --shell /bin/bash --gid rhcommon \
     --groups adm,sudo --base-dir $base_dir $user_name || exit $?

sudo mkdir -p $home_dir || exit $?
sudo chown $user_name:rhcommon $home_dir || exit $?
sudo chmod g+w $home_dir || exit $?

echo ""
echo "Enter a new password for user '$user_name' account:"
sudo passwd $user_name || exit $?

echo ""
sudo -u $user_name -g rhcommon \
     touch $home_dir/.sudo_as_admin_successful || exit $?
sudo chmod g+w $home_dir/.sudo_as_admin_successful || exit $?

function link {
  if [[ -f ~/$1 && ! -f $home_dir/$1 ]]; then
    sudo -u $user_name -g rhcommon ln -s ~/$1 $home_dir || exit $?
  fi
}

link .ICEauthority
link .Xauthority
link .aspell.en.prepl
link .aspell.en.pws
link .bashrc
link .gitconfig
link .inputrc
link .profile

if [[ -d ~/cmake && ! -d $home_dir/cmake ]]; then
  sudo -u $user_name -g rhcommon ln -s ~/cmake $home_dir || exit $?
fi

sudo apt install build-essential