#!/bin/bash

user_name="emacs"
package_name="$user_name"
base_dir="/home/rhpm/packages"
home_dir="$base_dir/$package_name"

common/rhpm-add $package_name || exit $?
common/mc-setup $package_name || exit $?

sudo apt install build-essential autoconf-archive autoconf texinfo \
         gnu-standards autoconf-doc libtool texlive-generic-recommended \
         texinfo-doc-nonfree libtool-doc wget dh-make gawk devhelp \
         spamassassin gnutls-bin guile-gnutls

sudo apt install libx11-dev xaw3dg-dev \
         libjpeg-dev libpng12-dev libgif-dev libtiff5-dev libncurses5-dev \
         libxft-dev librsvg2-dev libmagickcore-dev libmagick++-dev \
         libxml2-dev libgpm-dev libotf-dev libm17n-dev \
         libgnutls-dev libxpm-dev libgtk-3-dev \
         libmpfr-dev libmail-box-perl libmail-imapclient-perl \
         libmime-tools-perl libmojolicious-perl

sudo apt install libcairo2-doc libdatrie-doc libglib2.0-doc gmp-doc \
         libgmp10-doc gnutls-doc libgtk-3-doc libice-doc icu-doc\
         liblzma-doc m17n-docs ncurses-doc libpango1.0-doc librsvg2-doc \
         libsm-doc libthai-doc libwmf-doc libxcb-doc libxext-doc libxt-doc \
         gawk-doc guile-2.0-doc libgtk2.0-doc libmpfr-doc

# Additional utilities
sudo apt install clang-format-5.0

sudo -H -u $package_name -g rhcommon \
     git clone git://git.savannah.gnu.org/emacs.git \
               $home_dir/git || exit $?

cd $home_dir/git || exit $?

sudo -H -u $package_name -g rhcommon \
     ./autogen.sh all

sudo -H -u $package_name -g rhcommon \
     ./configure --with-xft

sudo -H -u $package_name -g rhcommon \
     make bootstrap docs

sudo -H -u $package_name -g rhcommon \
     make install prefix=/usr/local

sudo bash -c \
     "find  $home_dir/git -type f -print0 | xargs -0 chmod g+rw" || exit $?
sudo bash -c \
     "find  $home_dir/git -type d -print0 | xargs -0 chmod g+rws" || exit $?
sudo chmod g+rws /usr/local/share/emacs/site-lisp || exit $?
