#!/bin/bash

user_name="$1"
home_dir="/home/rhpm/packages/$user_name"

if [[ ! -d $home_dir/.local/var/log ]]; then
  sudo -u $user_name -g rhcommon \
       mkdir -p $home_dir/.local/var/log || exit $?
fi

if [[ ! -f $home_dir/.local/var/xsel.log ]]; then
  sudo -u $user_name -g rhcommon \
       touch $home_dir/.local/var/log/xsel.log || exit $?
fi

if [[ ! -d $home_dir/bin ]]; then
  sudo -u $user_name -g rhcommon mkdir $home_dir/bin || exit $?
fi

if [[ ! -f $home_dir/bin/f2clip ]]; then
  sudo -u $user_name -g rhcommon ln -s ~/bin/f2clip $home_dir/bin || exit $?
fi

if [[ -f ~/.selected_editor && ! -f $home_dir/.selected_editor ]]; then
  sudo -u $user_name -g rhcommon ln -s ~/.selected_editor $home_dir || exit $?
fi

if [[ ! -d $home_dir/.config/mc ]]; then
  sudo -u $user_name -g rhcommon mkdir -p $home_dir/.config/mc || exit $?
  sudo ln ~/.config/mc/ini $home_dir/.config/mc || exit $?
  sudo ln ~/.config/mc/mc.keymap $home_dir/.config/mc || exit $?
fi
