#!/bin/bash

if [[ ! $(getent group rhcommon) ]]; then
  sudo groupadd rhcommon || exit $?
  sudo usermod -a -G rhcommon `id -u -n` || exit $?
fi

sudo useradd --system --shell /bin/bash --gid rhcommon \
     --groups adm,sudo rhpm || exit $?

sudo mkdir -p /home/rhpm/packages || exit $?
sudo chown rhpm:rhcommon /home/rhpm || exit $?
sudo chmod g+w /home/rhpm || exit $?
sudo chown rhpm:rhcommon /home/rhpm/packages || exit $?
sudo chmod g+w /home/rhpm/packages || exit $?

echo ""
echo "Enter a new password for user 'rhpm' account:"
sudo passwd rhpm || exit $?

echo ""
sudo -u rhpm -g rhcommon touch /home/rhpm/.sudo_as_admin_successful || exit $?
sudo chmod g+w /home/rhpm/.sudo_as_admin_successful || exit $?

sudo chgrp rhcommon ~/.ICEauthority || exit $?
sudo chmod g+rw ~/.ICEauthority || exit $?

sudo chgrp rhcommon ~/.Xauthority || exit $?
sudo chmod g+rw ~/.Xauthority || exit $?

function link {
  if [[ -f ~/$1 && ! -f /home/rhpm/$1 ]]; then
    sudo chown `id -u -n`:rhcommon ~/$1 || exit $?
    sudo chmod g+w ~/$1 || exit $?
    sudo -u rhpm -g rhcommon ln -s ~/$1 /home/rhpm || exit $?
  fi
}

link .ICEauthority
link .Xauthority
link .aspell.en.prepl
link .aspell.en.pws
link .bashrc
link .gitconfig
link .inputrc
link .profile
