#!/bin/bash

user_name="rtags"
package_name="$user_name"
base_dir="/home/rhpm/packages"
home_dir="$base_dir/$package_name"

common/rhpm-add $package_name || exit $?
common/mc-setup $package_name || exit $?

sudo apt install clang libclang-dev libssl-dev lua5.3 liblua5.3-0 || exit $?

sudo -H -u $package_name -g rhcommon \
     git clone --recursive https://github.com/Andersbakken/rtags.git \
               $home_dir/git || exit $?

if [[ ! -d $home_dir/build ]]; then
  sudo -u $package_name -g rhcommon \
       mkdir -v $home_dir/build || exit $?
else
  sudo -u $package_name -g rhcommon \
       rm -v -f -R $home_dir/build/* || exit $?
fi

cd $home_dir/build || exit $?

sudo -H -u $package_name -g rhcommon \
     cmake -DCMAKE_TOOLCHAIN_FILE=$home_dir/cmake/gnu-gcc.cmake \
           ../git

sudo -H -u $package_name -g rhcommon \
     make || exit $?

sudo -H -u $package_name -g rhcommon \
     make install|| exit $?
