#!/bin/bash

user_name="rtags"
package_name="$user_name"
base_dir="/home/rhpm/packages"
home_dir="$base_dir/$package_name"

sudo apt install clang libclang-dev libssl-dev lua5.3 liblua5.3-0 || exit $?

sudo -H -u $package_name -g rhcommon \
     git clone --recursive https://github.com/ramblehead/rtags.git \
               $home_dir/git || exit $?
