#!/bin/bash

./rtags-build || exit $?

user_name="rtags"
package_name="$user_name"
base_dir="/home/rhpm/packages"
home_dir="$base_dir/$package_name"

cd $home_dir/build || exit $?

sudo -H -u $package_name -g rhcommon \
     make install|| exit $?
