#!/bin/bash

if ls -1qA /home/rhpm/packages | grep -q .; then
  echo "$(basename "$0"): /home/rhpm/packages is not" \
       "empty: remove all packages first"
  exit
fi

sudo userdel rhpm --remove
sudo groupdel rhcommon

#sudo chgrp `id -g -n` ~/.ICEauthority || exit $?
#sudo chgrp `id -g -n` ~/.Xauthority || exit $?

function rstgrp {
  if [[ -f ~/$1 ]]; then
    sudo chown `id -u -n`:`id -g -n` ~/$1 || exit $?
  fi
}

rstgrp .ICEauthority
rstgrp .Xauthority
rstgrp .aspell.en.prepl
rstgrp .aspell.en.pws
rstgrp .bashrc
rstgrp .gitconfig
rstgrp .inputrc
rstgrp .profile

sudo chmod g-rw ~/.ICEauthority || exit $?
sudo chmod g-rw ~/.Xauthority || exit $?

sudo chown root:root /usr/local
sudo chmod g-ws /usr/local
sudo sh -c "find /usr/local -type d -print0 | xargs -0 chown root:root"
sudo sh -c "find /usr/local -type d -print0 | xargs -0 chmod g-ws"
