#!/bin/bash

if ls -1qA /home/rhpm/packages | grep -q .; then
  echo "$(basename "$0"): /home/rhpm/packages is not" \
       "empty: remove all packages first"
  exit
fi

sudo userdel rhpm --remove
sudo groupdel rhcommon

sudo chgrp `id -g -n` ~/.ICEauthority || exit $?
sudo chmod g-rw ~/.ICEauthority || exit $?

sudo chgrp `id -g -n` ~/.Xauthority || exit $?
sudo chmod g-rw ~/.Xauthority || exit $?

function rstgrp {
  if [[ -f ~/$1 ]]; then
    sudo chown `id -u -n`:`id -g -n` ~/$1 || exit $?
  fi
}

rstgrp .ICEauthority
rstgrp .Xauthority
rstgrp .aspell.en.prepl
rstgrp .aspell.en.pws
rstgrp .bashrc
rstgrp .gitconfig
rstgrp .inputrc
rstgrp .profile
