#!/bin/bash

if [[ ! -d /home/rhpm/.local/var/log ]]; then
  sudo -u rhpm -g rhcommon mkdir -p /home/rhpm/.local/var/log || exit $?
fi

if [[ ! -f /home/rhpm/.local/var/xsel.log ]]; then
  sudo -u rhpm -g rhcommon touch /home/rhpm/.local/var/log/xsel.log || exit $?
fi

if [[ ! -d /home/rhpm/bin ]]; then
  sudo -u rhpm -g rhcommon mkdir /home/rhpm/bin || exit $?
fi

if [[ ! -f /home/rhpm/bin/f2clip ]]; then
  sudo -u rhpm -g rhcommon ln -s ~/bin/f2clip /home/rhpm/bin || exit $?
fi

if [[ ! -d /home/rhpm/.config/mc ]]; then
  sudo chmod g+rx-w ~/.config/mc
  sudo chgrp rhcommon ~/.config/mc
  sudo chgrp rhcommon ~/.config/mc/ini
  sudo chmod g+rw ~/.config/mc/ini
  sudo chgrp rhcommon ~/.config/mc/mc.keymap
  sudo chmod g+rw ~/.config/mc/mc.keymap
  sudo -u rhpm -g rhcommon mkdir -p /home/rhpm/.config/mc || exit $?
  sudo ln ~/.config/mc/ini /home/rhpm/.config/mc || exit $?
  sudo ln ~/.config/mc/mc.keymap /home/rhpm/.config/mc || exit $?
fi
